### ISSUE TITLE
MAINT - Add multiple maintainers

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/accessible-pygments#12]
To reduce redundancy, it would be best to add more maintainers to:

- the package itself
- [PyPI](https://pypi.org/project/accessible-pygments/)
- conda-forge

**Comment by steff456** [comment]
I already added @trallard as maintainer in 

- [x] the package
- [x] PyPI - https://pypi.org/project/accessible-pygments/
- [x] conda-forge - https://github.com/conda-forge/accessible-pygments-feedstock/pull/2

So I'm closing this issue!
