### ISSUE TITLE
diff lexer is not covered

### ISSUE THREAD

**Issue by 12rambau** [Quansight-Labs/accessible-pygments#32]
We use accessible-pygments in the pydata-sphinx-theme and recently a user complained about the parsing of a specific lexer: `diff`

After changing the pygment style the styling came back so my guess is that you are not covering some of the tags related to this lexer. 

![](https://user-images.githubusercontent.com/13836216/274412558-7a83f8a1-758d-419d-99f1-3d13e1810bc7.png)

See https://github.com/pydata/pydata-sphinx-theme/issues/1506 for more details.

**Comment by K20shores** [comment]
Duplicate of #31

**Comment by 12rambau** [comment]
I'm so slow ;-)
