### ISSUE TITLE
Could the light themes use a background color that is more distinct from `#ffffff`?

### ISSUE THREAD

**Issue by pradyunsg** [Quansight-Labs/accessible-pygments#38]
Hi there! 👋🏽 

I was looking into switching [Furo](https://pradyunsg.me/furo/) over to using one of these themes by default, and it looks like the background on most of the light themes is very close to white -- that doesn't really make code blocks visually distinct in the current design of Furo's code blocks.

Could the light themes use a background color that is more distinct from `#ffffff`? Other than gotthard[^1], all the light themes use a background very close to `#ffffff`. 😅 

I'm mostly asking this since I noticed that that in #30 / #33, the background colors being tested against are `#f3f4f5` in addition to the pygments theme's `#fefefe`. This seems to be for better behaviours with pydata-sphinx-theme, where the pygments themes' [background colors are overriden by the Sphinx theme's CSS](https://github.com/Quansight-Labs/accessible-pygments/issues/30). I'd like to avoid overriding default pygments theme colors in Furo.

[^1]: Which uses a non-neutral color for comments, hence my hesitation in using that as the default.

**Comment by trallard** [comment]
Hey again. 

> I was looking into switching [Furo](https://pradyunsg.me/furo/) over to using one of these themes by default, and it looks like the background on most of the light themes is very close to white -- that doesn't really make code blocks visually distinct in the current design of Furo's code blocks.

First, it is great to know you are considering switching, so I am keen to help find something that would work for Furo. 

I agree that a current limitation is that most of the light themes use a background quite close to white (which, in turn, raises issues like the ones in #30, among others)

> Could the light themes use a background color that is more distinct from #ffffff? Other than gotthard[1](https://github.com/Quansight-Labs/accessible-pygments/issues/38#user-content-fn-1-c3078588d859301c53e4a1b1840aee8b), all the light themes use a background very close to #ffffff. 😅

We could look into improving that for the current light themes (but that might take a while, to be honest).

Alternatively, and perhaps a quicker thing to do to help you migrate, would be to improve the contrast/colours from the `tango` and `native` themes you currently use. WDYT?

**Comment by pradyunsg** [comment]
> First, it is great to know you are considering switching, so I am keen to help find something that would work for Furo.

❤️

> Alternatively, and perhaps a quicker thing to do to help you migrate, would be to improve the contrast/colours from the tango and native themes you currently use. WDYT?

TBH, I'm in no hurry and adding a new theme would work well for me!

I am hoping to use one of the existing dark mode themes from here instead of native (I'm not particularly keen on native itself TBH, it just happened to be the theme with the least-worst contrast story with a relatively neutral background IIRC).

Overall, I'm happy with either approach here porting the light theme Furo's using OR tweaking the colours on an existing theme, with a mild preference for taking whichever is lower effort for y'all![^1]

[^1]: I suggested this partly since it _looked_ like a low-cost change once #33 goes through since it'd be a case of changing a single variable rather than adding a new theme as a whole.

**Comment by trallard** [comment]
Now that we have #30 merged, we can follow up on this issue - we identified a good grey candidate in https://github.com/Quansight-Labs/accessible-pygments/pull/33#issuecomment-1941846397 so we can replace that directly in `a11y-light` and maybe another one theme?

This would allow @pradyunsg  to make the swap in Furo.

**Comment by trallard** [comment]
So now that #56 is in, we have at least one theme with a background that is more distinct from pure white.

We will continue to work on improvements to the themes but in the meantime this seems to address your needs @pradyunsg

**Comment by pradyunsg** [comment]
FYI: The next Furo release will switch defaults to accessible-pygments!

https://github.com/pradyunsg/furo/commit/be0072df861133ce0b16ce5b83049924b95c7cee

Happy new year folks!
