### ISSUE TITLE
Time for new release?

### ISSUE THREAD

**Issue by yuzibo** [Quansight-Labs/accessible-pygments#50]
Hi,

We had 0.0.4 almost one year ago, do we have plan to push new release recently?

I am packaging the [package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1029009) with 0.0.4, but it is hard to run test during the build. Now we have switched to pyproject build end, so I think it is friendly to packager maybe.

**Comment by yuzibo** [comment]
> but it is hard to run test during the build.

No. It is easy. just not use pytest like other Python project.

**Comment by trallard** [comment]
Hi @yuzibo. Thanks for opening an issue! I was indeed thinking we needed a release, as there have been a lot of changes recently, some of which should make packaging and distribution easier.

@gabalafou, I would like to get the only other item in a new release is https://github.com/Quansight-Labs/accessible-pygments/issues/38 (changing background colour). Can we do this for a release late this week/early next week?

**Comment by trallard** [comment]
@yuzibo I just made a new release for the package https://pypi.org/project/accessible-pygments/ 
let me know if you encounter any issues

**Comment by yuzibo** [comment]
thanks!
